-- Crearea tabelului de audit
CREATE TABLE audit_ldd (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  action_type  VARCHAR2(30),
  object_type  VARCHAR2(30),
  object_name  VARCHAR2(128),
  username     VARCHAR2(30),
  timestamp    TIMESTAMP
);

-- Crearea trigger-ului LDD
CREATE OR REPLACE TRIGGER audit_ldd_trigger
AFTER DROP OR ALTER OR CREATE ON DATABASE
DECLARE
  v_username VARCHAR2(30);
BEGIN
  -- Obtinerea numele de utilizator curent
  SELECT ora_login_user INTO v_username FROM dual;

  -- Verificarea daca utilizatorul este 'BOTE'
  IF v_username = 'BOTE' THEN
    -- Inserarea inregistrarii in tabelul de audit
    INSERT INTO audit_ldd(action_type, object_type, object_name, username, timestamp)
    VALUES(ora_sysevent, ora_dict_obj_type, ora_dict_obj_name, v_username, SYSTIMESTAMP);
  ELSE
    -- Ridicarea exceptiei daca un alt utilizator incearca sa efectueze LDD
    RAISE_APPLICATION_ERROR(-20001, 'Nu ai permisiunea de a modifica schema bazei de date.');
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    -- Gestionare exceptiile aici, daca este necesar
    NULL;
END;
/

CREATE TABLE meniu (
  id_preparat NUMBER PRIMARY KEY,
  nume        VARCHAR2(100) NOT NULL,
  pret        NUMBER(5,2) NOT NULL
);

DROP TABLE meniu;

select*
from audit_ldd;
